# golangci-lint configuration
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - website/node_modules
    - internal/server/frontend/node_modules

linters:
  enable:
    # Core linters
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Check for unused code

    # Additional recommended linters
    - misspell      # Fix commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security issues
    - gocritic      # Opinionated Go linter
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters
    - prealloc      # Slice preallocation
    - nolintlint    # Ill-formed or insufficient nolint directives

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true

  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: true  # Not all packages need comments

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (too noisy)
      - G304  # File path from variable (common pattern)

  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - emptyFallthrough
      - equalFold
      - flagDeref
      - nilValReturn
      - regexpMust
      - sloppyLen
      - weakCond

  misspell:
    locale: US

  unparam:
    check-exported: false

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - website/node_modules
    - internal/server/frontend/node_modules
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocritic

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"  # Empty branch

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Disable certain checks for embed directives
    - path: ".*\\.go"
      text: "embed"
      linters:
        - typecheck

  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
